name: Accsys_Pay
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  page_transition: ^2.0.4
  intl: ^0.17.0
  flutter_credit_card: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_calendar_week: ^3.0.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  smooth_page_indicator: ^0.2.3
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  razorpay_flutter: ^1.1.1
  lottie: ^1.4.1
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.1.3
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.5
  google_fonts: ^3.0.1
  nb_utils: ^5.0.8
  shimmer: ^2.0.0
  awesome_dialog: ^3.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter_barcode_scanner: ^2.0.0
  dots_indicator: ^3.0.0
  syncfusion_flutter_charts: ^20.4.41
  font_awesome_flutter: ^10.4.0
  contacts_service: ^0.6.3
  autocomplete_textfield: ^2.0.1
  quiver: ^3.2.1
  sizer: ^2.0.15
  equatable: ^2.0.5
  flutter_dash: ^1.0.0
  firebase_messaging: ^14.6.5
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  upgrader: ^6.5.0

  # book_my_seat: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/images/services/
    - assets/images/logo/
    - assets/images/walletApp/
    - assets/images/toDoList/
    - assets/icons/
    - assets/lottie/
    - assets/icons/
    - assets/users/
    - assets/mobile_card/
    - assets/electricity_company/
    - assets/airlines_logo/
    - assets/moive/
    - assets/offers/
    - assets/rewards/
    - assets/social_media/
    - assets/shopping_category/
    - assets/shopping_deals/
    - assets/products/
    - assets/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
